### ISSUE TITLE
17.30 is out

### ISSUE THREAD

**Issue by ranisalt** [corngood/archlinux-amdgpu#51]
Latest version of amdgpu-pro 17.20 was just launched by AMD some days ago. It seems to be compatible with more recent versions of Linux (up to 4.11) but the contents of the package are a bit different, so you might need change the script.

**Comment by znmeb** [comment]
How about compatibility with X / Mesa / OpenCL libraries? Is their Linux support still just Ubuntu 16.04 LTS and RHEL/CentOS?

**Comment by ranisalt** [comment]
Well, release notes as always are unclear, but I hope to see support for more up to date X and others too. I can't really install Ubuntu here just to test, so...

**Comment by znmeb** [comment]
If it shows up in AUR I'll check the upstream release notes / bug trackers and see if there have been some closed bugs.

**Comment by Darkhogg** [comment]
17.30 is out now, with support for Xorg 1.19 and Linux 4.10, it would be nice if @corngood updated it.

**Comment by corngood** [comment]
I'm happy to take a PR and release it, but I'm primarily using NixOS/Mesa these days.  It's hard to justify putting time into this now that Mesa is in such good shape.

If anyone's interested in taking over maintainership, let me know.

**Comment by ranisalt** [comment]
My motherboard died and I couldn't do it currently :(

**Comment by Tuerai** [comment]
If you could give me some instructions for how to try to build the package with the newest driver for a different distro from AMD's website, I'd give it a shot.

**Comment by corngood** [comment]
@Tuerai first step would be to make sure you can build 17.10 from this repo.  The CI script shows the dependencies.  Then you just need to update the versions, tarball hash etc. and see how broken things are.

I'm going to try to get 17.30 working on nixos right now, which should give me an idea of the problems we're going to run into.

**Comment by corngood** [comment]
A couple of notes on 17.30:

- structure seems mostly similar to 17.10
- kernel module doesn't load with linux 4.9 (missing drmbuf_ops symbol)
- kernel module doesn't build with 4.12

It's probably not worth testing with anything other than 4.10.

**Comment by corngood** [comment]
I pushed #52 with the initial changes for 17.30.  I was able to get it running on NixOS, but I haven't been able to test this PKGBUILD other than via CI.

I'd appreciate it if anyone can test it, but please be careful.  Make sure you are comfortable recovering your system with a fallback kernel and no X.

**Comment by archyboy** [comment]
How do i actually build this and install this?

**Comment by archyboy** [comment]
Its not supposed to build the amdgpu-pro-core.tar.xz? It seems to be missing?

**Comment by heavysink** [comment]
Anyone who want to try 17.30 can go to Archlinuxcn repository. I have successfully built, installed and ran it without problem with my 4.13.6 kernel + Xorg 1.19.5. Though amdgpu-pro-dkms still have problem, the driver runs fine on my machine without installing dkms module.

Instruction to add repo:
https://wiki.archlinux.org/index.php/unofficial_user_repositories#archlinuxcn

@corngood The PKGBUILD is here:
https://github.com/archlinuxcn/repo/tree/master/amdgpu-pro-installer

**Comment by brainpower** [comment]
It will run with the OSS kernel module then, but since that one is in decent shape nowadays, there shouldn't be any problems (probably).

And since mesa's libgl outperforms AMDGPU-PRO's libgl with most workloads [1], most people should even be fine with a mesa-only stack.
The only things, one might want AMDGPU-PRO for is Vulkan and maybe OpenCL or some very vendor specific things.
RADV's performance is good enough for me, but I don't know how it compares to AMD's Vulkan implementation currently.

[1] https://www.phoronix.com/scan.php?page=article&item=amdgpu-1730-radeonsi

**Comment by Darkhogg** [comment]
@brainpower And to have sound over HDMI :disappointed:

**Comment by heavysink** [comment]
@brainpower @Darkhogg I used to agree with you until I come across some proprietary software that have strictly banned the use of mesa... (e.g. detect the driver and says "you are using open-source mesa libGL. Please switch to proprietary libGL. Exiting..."). And some other software, like MATLAB, will disable hardware OpenGL rendering when using mesa.

Although mesa's libgl is outperforming AMDGPU-PRO in most of the aspects, there are some software that cannot run on mesa at all...

**Comment by brainpower** [comment]
Well, that comment about mesa was meant as just a side note, the main point was that the AMDGPU-PRO userland stuff, (e.g. libGL and other things) should work fine with the OSS kernel module nowadays.
And applications only seem to care about the correct userland stuff...
If I find some time for it (probably at the weekend), I'll try to work on getting your changes into the gen-PKGBUILD.py script... 

On a side note, though: 
I think it's sad that applications rule out implementations on principle and not based on needed GL extensions or features...

**Comment by riddicc** [comment]
the RX550 cannot do 2560x1080@60Hz with amdgpu&mesa17.4&manjaroLinux,
but it can with amdgpu-pro17.30&ubuntu16...
the proprietary driver is even 20% faster than mesa17.4...
amdgpu-pro17.10 on manjaroLinux is slow and needs an old kernel... :)

i dont like to move to another distribution (that's why i like rolling releases, i guess)... :)
manjaroLinux can do 2560x1080@40Hz with slow (but stable) OpenGL support...

the archlinuxcn repo version of amdgpu-pro17.40 has the same problem (slow&low vfreq)...

so the proprietary driver would be nice for that RX550... :)

**Comment by mirh** [comment]
Situation for open driver is going to drastically change when DC lands in 4.15. 
Manjaro atm is [not](https://github.com/manjaro/release-plan/issues/37#issuecomment-336743023) focused at all on -PRO, you should ping on the forums if really any. 
Support for it, regardless, would first depend on #52 (I'm not sure why it's still pending merge?)

Last but not least.. Idk, what's still the point of this issue? Dev knows the thing is outdated and #53, 17.40 is out
And it's sad to see duplication between repos. Maybe @corngood could add @heavysink to maintainers list if it's not a lot active anymore?

**Comment by heavysink** [comment]
@riddicc feel free to go back to this commit and recompile 17.30 locally.

https://github.com/archlinuxcn/repo/tree/e066077e0c60c98b6178e9f1fe55e4c905d68028/amdgpu-pro-installer

**Comment by svenstaro** [comment]
This should be closed.
